{
 "title": "Análise Eficiência",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "texto_norvi_wifi" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "texto_norvi_wifi" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m³/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "texto_norvi_wifi" }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 0 },
   "targets": [
    { "topic": "texto_norvi_wifi" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT POTENCIA_ATIVA FROM INOVATEC_IOT.EFETIVO_MEDIDOR LIMIT 50 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT POTENCIA_REATIVA FROM INOVATEC_IOT.EFETIVO_MEDIDOR LIMIT 50 "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT FATOR_POTENCIA_LEITURA FROM INOVATEC_IOT.EFETIVO_MEDIDOR "
    }
   ]
  },
  {
   "title": "MEDIÇÃO PAINEL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT POTENCIA_APARENTE AS \"POTENCIA APARENTE\", POTENCIA_ATIVA AS \"POTENCIA ATIVA\", POTENCIA_REATIVA AS \"POTENCIA REATIVA\", TIMESTAMP FROM INOVATEC_IOT.EFETIVO_MEDIDOR"
    }
   ]
  },
  {
   "title": "DADOS NOMINAIS X DADOS REAIS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT\r\n  FROM_UNIXTIME($__unixEpochFrom()) AS \"time\",\r\n  CORRENTE_NOMINAL AS \"CORRENTE_NOMINAL\"\r\nFROM\r\n  DADOS_MOTOR\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n  FROM_UNIXTIME($__unixEpochTo()) AS \"time\",\r\n  CORRENTE_NOMINAL AS \"value\"\r\nFROM\r\n  DADOS_MOTOR\r\n\r\nORDER BY\r\n  \"time\""
    },
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT CORRENTE_LEITURA, TIMESTAMP FROM INOVATEC_IOT.EFETIVO_MOTOR"
    },
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT\r\n  FROM_UNIXTIME($__unixEpochFrom()) AS \"time\",\r\n  FATOR_SERVICO_CALC AS \"FATOR DE SERVIÇO\"\r\nFROM\r\n  DADOS_MOTOR\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n  FROM_UNIXTIME($__unixEpochTo()) AS \"time\",\r\n  FATOR_SERVICO_CALC AS \"value\"\r\nFROM\r\n  DADOS_MOTOR\r\n\r\nORDER BY\r\n  \"time\""
    }
   ]
  },
  {
   "title": "VAZAO X CORRENTE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "Dashboards",
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT CORRENTE_LEITURA as CORRENTE, TIMESTAMP FROM INOVATEC_IOT.EFETIVO_MOTOR "
    },
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT VAZAO_LEITURA AS VAZAO, TIMESTAMP FROM INOVATEC_IOT.EFETIVO_HIDRAULICO"
    }
   ]
  },
  {
   "title": "VAZÃO X PRESSAO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "INOVATEC_IOT",
     "rawSql": "SELECT TIMESTAMP, PRESSAO_LEITURA AS PRESSÃO, VAZAO_LEITURA AS VAZÃO FROM INOVATEC_IOT.EFETIVO_HIDRAULICO "
    }
   ]
  }
 ]
}