CREATE DATABASE INOVATEC_IOT;
USE INOVATEC_IOT;


CREATE TABLE DADOS_MOTOR
(
ID_PNL INT(4),
NOME_BP VARCHAR(15) NOT NULL,
POTENCIA FLOAT (6, 2) NOT NULL,
CORRENTE_NOMINAL FLOAT(6, 3) NOT NULL,
FATOR_SERVICO FLOAT(3, 2) NOT NULL,
FATOR_POTENCIA FLOAT(3, 2) NOT NULL,

PRIMARY KEY (ID_PNL)
);

CREATE TABLE EFETIVO_MOTOR
(
TIMESTAMP timestamp DEFAULT current_timestamp,
ID_PNL INT(4),
NOME_BP VARCHAR(15),
CORRENTE_LEITURA FLOAT(6, 3) NOT NULL,
FREQUENCIA_LEITURA FLOAT(4, 2) NOT NULL,

FOREIGN KEY (ID_PNL) REFERENCES DADOS_MOTOR(ID_PNL)
);

CREATE TABLE EFETIVO_MEDIDOR
(
TIMESTAMP timestamp DEFAULT current_timestamp,
ID_PNL INT(4),
POTENCIA_ATIVA FLOAT(6, 3) NOT NULL,
POTENCIA_APARENTE FLOAT(6, 3) NOT NULL,
POTENCIA_REATIVA FLOAT(6, 3) NOT NULL,
FATOR_POTENCIA_LEITURA FLOAT(6, 3) NOT NULL,

FOREIGN KEY (ID_PNL) REFERENCES DADOS_MOTOR(ID_PNL)
);

CREATE TABLE EFETIVO_HIDRAULICO
(
TIMESTAMP TIMESTAMP DEFAULT current_timestamp,
ID_PNL INT(4) REFERENCES DADOS_MOTOR(ID_PNL),
PRESSAO_LEITURA FLOAT(5, 2) NOT NULL,
VAZAO_LEITURA FLOAT(5, 2) NOT NULL
);

INSERT INTO DADOS_MOTOR 
VALUES(1212, 'BP1', 10, 12.5, 1.15, 0.89);

INSERT INTO EFETIVO_MOTOR
VALUES(current_timestamp(), 1212, 'BP1', 8.5, 60);

SELECT * FROM DADOS_MOTOR;
SELECT * FROM EFETIVO_MOTOR



